### ISSUE TITLE
Xcode Coverage Script Failing

### ISSUE THREAD

**Issue by morganzellers** [wwt/Workflow#27]
https://community.sonarsource.com/t/sonarswift-code-coverage/17240/5

Something is wrong with our xcode coverage shell script but I haven't the faintest idea what, it is likely unrelated to the PR.

_Originally posted by @Tyler-Keith-Thompson in https://github.com/wwt/Workflow/issues/26#issuecomment-846713141_

**Comment by morganzellers** [comment]
[Slather Github Page](https://github.com/SlatherOrg/slather)

[Information on caching installed dependencies for Github Actions.](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows) Something we may be interested in doing if we switch to installing Slather to do this instead of the shell script.

**Comment by Tyler-Keith-Thompson** [comment]
I looked at Slather and find it a little scary. They have an open call for maintainers and have not responded to many issues.

Also they don't support projects like ours without an xcodeproj. I can't find the link to save my life right now but I saw an issue for 2018 asking them to add support for people creating SwiftPM packages.

I'm also a little annoyed with SonarCloud because they have the issue posted all over their site with no clear resolution

**Comment by Tyler-Keith-Thompson** [comment]
All this to say maybe this is a kick in the pants to move away from SonarCloud

**Comment by morganzellers** [comment]
Referenced this context in [this](https://github.com/wwt/Workflow/projects/1#card-61588681) card for SonarCloud vs Coverity research

**Comment by Tyler-Keith-Thompson** [comment]
Found it! [here](https://github.com/SlatherOrg/slather/issues/466) is the issue from slather that asks for SwiftPM support
